# Generated by Django 4.2 on 2024-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Porque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('subarea', models.CharField(blank=True, max_length=100, null=True)),
                ('maquina', models.CharField(blank=True, max_length=100, null=True)),
                ('pilar', models.CharField(blank=True, max_length=100, null=True)),
                ('impacto', models.TextField(blank=True, null=True)),
                ('kpi_iceo', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi_secundario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('miembros_equipo', models.ManyToManyField(to='MiniProyecto.miembroequipo')),
            ],
        ),
    ]
