# Generated by Django 4.2 on 2024-10-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porque',
            new_name='Miniproyecto',
        ),
    ]
