# Generated by Django 4.2 on 2024-10-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0002_rename_porque_miniproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_Preventiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_Preventiva_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_Preventiva_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_Preventiva_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_correctiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_correctiva_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_correctiva_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Accion_correctiva_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Estandarizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Estandarizacion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Estandarizacion_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Estandarizacion_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Expansion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Expansion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Expansion_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Expansion_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_cierre_paso4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_cierre_paso4_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_cierre_paso4_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_cierre_paso4_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso1_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso1_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso1_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso2_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso2_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso2_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso3_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso3_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso3_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso4_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso4_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Fecha_compromiso4_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA_2',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA_3',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA_4',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA_5',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA_6',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA_7',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ISHIKAWA_8',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='MOC',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no aplica', 'No aplica')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='MOC_2',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no aplica', 'No aplica')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='MOC_3',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no aplica', 'No aplica')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='MOC_4',
            field=models.CharField(blank=True, choices=[('aplica', 'Aplica'), ('no aplica', 'No aplica')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz_2',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz_3',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz_4',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz_5',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz_6',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz_7',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Raiz_8',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable1',
            field=models.ManyToManyField(blank=True, related_name='responsable1', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable1_2',
            field=models.ManyToManyField(blank=True, related_name='responsable1_2', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable1_3',
            field=models.ManyToManyField(blank=True, related_name='responsable1_3', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable1_4',
            field=models.ManyToManyField(blank=True, related_name='responsable1_4', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable2',
            field=models.ManyToManyField(blank=True, related_name='responsable2', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable2_2',
            field=models.ManyToManyField(blank=True, related_name='responsable2_2', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable2_3',
            field=models.ManyToManyField(blank=True, related_name='responsable2_3', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable2_4',
            field=models.ManyToManyField(blank=True, related_name='responsable2_4', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable3',
            field=models.ManyToManyField(blank=True, related_name='responsable3', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable3_2',
            field=models.ManyToManyField(blank=True, related_name='responsable3_2', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable3_3',
            field=models.ManyToManyField(blank=True, related_name='responsable3_3', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable3_4',
            field=models.ManyToManyField(blank=True, related_name='responsable3_4', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable4',
            field=models.ManyToManyField(blank=True, related_name='responsable4', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable4_2',
            field=models.ManyToManyField(blank=True, related_name='responsable4_2', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable4_3',
            field=models.ManyToManyField(blank=True, related_name='responsable4_3', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Responsable4_4',
            field=models.ManyToManyField(blank=True, related_name='responsable4_4', to='MiniProyecto.miembroequipo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='areas_aplicacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion1_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion2_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion3_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion4_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion5_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion6_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='color_validacion7_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='como_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cómo ocurre? Describir desde el punto de vista físico el mecanismo de acción visibilizado en el momento.'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='condiciones_basicas',
            field=models.TextField(blank=True, null=True, verbose_name='Verificar condiciones básicas definidas e identificar desviaciones que impacten en el problema'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='cuando_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuándo ocurrió? Producción, arranque, saneado, cambio de formato, mantención, etc.'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='descripcion_senal',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la señal'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='donde_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Dónde ocurre? Producto, equipo, zona de la máquina, etc.'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ejecuto_lila',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Se ejecutó correctamente el LILA?'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='falla_funcional',
            field=models.TextField(blank=True, null=True, verbose_name='Falla funcional'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='imagen_falla',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_falla/'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='imagen_falla_funcional',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_fallas/'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='imagen_funcionamiento',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_funcionamiento/'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='lila_asociado',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Hay LILA asociado a la máquina?'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='mantenimiento_no_ejecutado',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Hay actividades de mantenimiento no ejecutadas asociadas a la falla funcional (revisar plan de 52 semanas)?'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='materiales_calidad',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Los materiales cumplen con las especificaciones de calidad?'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso2',
            field=models.TextField(blank=True, null=True, verbose_name='El modo de falla corresponde al evento o situación que causa la falla funcional. Ej: presión inestable por válvula rota, inspector detecta elemento extraño pero no lo rechaza, inspector no detecta elemento extraño, sulfatación de sensor de seguridad, etc.'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3_2',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3_3',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3_4',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3_5',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3_6',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3_7',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='modo_falla_paso3_8',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque1_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque2_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque3_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque4_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque5_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque6_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='porque7_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='principio_funcionamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Comprender el principio de funcionamiento de la máquina o proceso, incluyendo estándares y parámetros de trabajo'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='que_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué ocurre? ¿En qué parte de la máquina o material se visualiza el problema?'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='quien_presente',
            field=models.TextField(blank=True, null=True, verbose_name='¿Quién estaba presente cuando ocurrió? ¿El problema pasa en todos los turnos?'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='senal_antes',
            field=models.CharField(blank=True, choices=[('alarma', 'Alarma'), ('fuga', 'Fuga'), ('cavitacion', 'Cavitación'), ('ruido', 'Ruido'), ('otros', 'Otros'), ('nia', 'N/A')], max_length=100, null=True, verbose_name='Señal antes de que ocurra el problema'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='tarjetas_atrasadas',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Hay tarjetas atrasadas o pendientes asociadas a la falla funcional?'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('p', 'P'), ('gv', 'GV'), ('py', 'PY'), ('m', 'M')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='tipo_2',
            field=models.CharField(blank=True, choices=[('p', 'P'), ('gv', 'GV'), ('py', 'PY'), ('m', 'M')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='tipo_3',
            field=models.CharField(blank=True, choices=[('p', 'P'), ('gv', 'GV'), ('py', 'PY'), ('m', 'M')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='tipo_4',
            field=models.CharField(blank=True, choices=[('p', 'P'), ('gv', 'GV'), ('py', 'PY'), ('m', 'M')], max_length=100, null=True),
        ),
    ]
