# Generated by Django 4.2 on 2024-11-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0003_miniproyecto_accion_preventiva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproyecto',
            name='descripcion_senal',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='falla_funcional',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='quien_presente',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='senal_antes',
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='Resumen',
            field=models.TextField(blank=True, null=True, verbose_name='Resumen del problema'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='perdida',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuánto es la pérdida asociada? (horas, kilos, cajas, botellas, dinero, etc)'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='quien_intervino',
            field=models.TextField(blank=True, null=True, verbose_name='¿Quién pudo influir o interviene?'),
        ),
    ]
