# Generated by Django 4.2 on 2024-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0004_remove_miniproyecto_descripcion_senal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproyecto',
            name='Nombre_MP',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='ahorro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
