# Generated by Django 4.2 on 2024-11-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0005_miniproyecto_nombre_mp_miniproyecto_ahorro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproyecto',
            name='Nombre_MP',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
