# Generated by Django 4.2 on 2024-11-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0006_alter_miniproyecto_nombre_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproyecto',
            name='ahorro',
            field=models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='miniproyecto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=12, null=True),
        ),
    ]
