# Generated by Django 4.2 on 2024-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0007_alter_miniproyecto_ahorro_alter_miniproyecto_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproyecto',
            name='ahorro',
            field=models.DecimalField(blank=True, decimal_places=0, default='-', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='miniproyecto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=0, default='-', max_digits=12, null=True),
        ),
    ]
