# Generated by Django 4.2 on 2024-11-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0008_alter_miniproyecto_ahorro_alter_miniproyecto_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproyecto',
            name='ahorro',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='miniproyecto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ImagenFallaFuncional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_fallas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='MiniProyecto.miniproyecto')),
            ],
        ),
    ]
