# Generated by Django 4.2 on 2024-11-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0011_imagenminiproyecto_delete_imagenfallafuncional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniproyecto',
            old_name='Resumen',
            new_name='resumen',
        ),
    ]
