# Generated by Django 4.2 on 2024-11-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0012_rename_resumen_miniproyecto_resumen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproyecto',
            name='condiciones_basicas',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='ejecuto_lila',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='imagen_falla',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='lila_asociado',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='mantenimiento_no_ejecutado',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='materiales_calidad',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='modo_falla_paso2',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='tarjetas_atrasadas',
        ),
    ]
