# Generated by Django 4.2 on 2024-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0014_remove_miniproyecto_principio_funcionamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproyecto',
            name='condicion_basica',
            field=models.TextField(blank=True, null=True, verbose_name='¿Existe un estándar (procedimiento/instructivo/formato definido)?, ¿Es conocido por todos, existe un entrenamiento (Registro de capacitación/LUP) ?¿Cumple mantenciones preventivas?'),
        ),
    ]
