# Generated by Django 4.2 on 2024-11-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0015_alter_miniproyecto_condicion_basica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFuncionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_funcionamiento/')),
                ('miniproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_funcionamiento', to='MiniProyecto.miniproyecto')),
            ],
        ),
    ]
