# Generated by Django 4.2 on 2024-11-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0019_remove_miniproyecto_ishikawa_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproyecto',
            name='desarrollo',
            field=models.TextField(blank=True, null=True, verbose_name='Describa causa raíz'),
        ),
        migrations.AlterField(
            model_name='miniproyecto',
            name='ISHIKAWA',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True, verbose_name='Escoja una de las 6 M'),
        ),
    ]
