# Generated by Django 4.2 on 2024-11-07 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0020_miniproyecto_desarrollo_alter_miniproyecto_ishikawa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Accion_correctiva',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Accion_correctiva_2',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Accion_correctiva_3',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Accion_correctiva_4',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Fecha_compromiso1',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Fecha_compromiso1_2',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Fecha_compromiso1_3',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Fecha_compromiso1_4',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Responsable1',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Responsable1_2',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Responsable1_3',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='Responsable1_4',
        ),
    ]
