# Generated by Django 4.2 on 2024-11-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0024_miniproyecto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproyecto',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='tipo_2',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='tipo_3',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='tipo_4',
        ),
    ]
