# Generated by Django 4.2 on 2024-11-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0026_miniproyecto_estado_2_miniproyecto_estado_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproyecto',
            name='imagen_antes',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_antes/'),
        ),
        migrations.AddField(
            model_name='miniproyecto',
            name='imagen_despues',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_despues/'),
        ),
    ]
