# Generated by Django 4.2 on 2024-11-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0027_miniproyecto_imagen_antes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDespues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_miniproyectos_despues/')),
                ('miniproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_despues', to='MiniProyecto.miniproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_miniproyectos_antes/')),
                ('miniproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_antes', to='MiniProyecto.miniproyecto')),
            ],
        ),
    ]
