# Generated by Django 4.2 on 2024-11-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0028_imagendespues_imagenantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenantes',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_antes/'),
        ),
        migrations.AlterField(
            model_name='imagendespues',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_despues/'),
        ),
    ]
