# Generated by Django 4.2 on 2024-11-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0029_alter_imagenantes_imagen_alter_imagendespues_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagendespues',
            name='miniproyecto',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='imagen_antes',
        ),
        migrations.RemoveField(
            model_name='miniproyecto',
            name='imagen_despues',
        ),
        migrations.DeleteModel(
            name='ImagenAntes',
        ),
        migrations.DeleteModel(
            name='ImagenDespues',
        ),
    ]
