# Generated by Django 4.2 on 2024-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0030_remove_imagendespues_miniproyecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenminiproyecto',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_funcional/'),
        ),
        migrations.AlterField(
            model_name='miniproyecto',
            name='imagen_falla_funcional',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='miniproyecto',
            name='imagen_funcionamiento',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
