# Generated by Django 4.2 on 2024-11-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0031_alter_imagenminiproyecto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproyecto',
            name='imagen_funcionamiento',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_funcionamiento/'),
        ),
    ]
