# Generated by Django 4.2 on 2024-11-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0032_alter_miniproyecto_imagen_funcionamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproyecto',
            name='imagen_falla_funcional',
        ),
    ]
