# Generated by Django 4.2 on 2024-11-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0033_remove_miniproyecto_imagen_falla_funcional'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproyecto',
            name='imagen_falla_funcional',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
