# Generated by Django 4.2 on 2024-11-11 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0037_alter_imagenminiproyecto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniproyecto',
            name='imagen_antes',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_antes/'),
        ),
        migrations.CreateModel(
            name='ImagenAntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_miniproyectos_antes/')),
                ('miniproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_antes', to='MiniProyecto.miniproyecto')),
            ],
        ),
    ]
