# Generated by Django 4.2 on 2024-11-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0038_miniproyecto_imagen_antes_imagenantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenantes',
            old_name='imagen',
            new_name='imagen2',
        ),
    ]
