# Generated by Django 4.2 on 2024-11-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0039_rename_imagen_imagenantes_imagen2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniproyecto',
            name='imagen_antes',
        ),
        migrations.DeleteModel(
            name='ImagenAntes',
        ),
    ]
