# Generated by Django 4.2 on 2024-11-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiniProyecto', '0040_remove_miniproyecto_imagen_antes_delete_imagenantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPaso2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_paso2/')),
                ('miniproyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_paso2', to='MiniProyecto.miniproyecto')),
            ],
        ),
    ]
