# Generated by Django 5.0.7 on 2024-08-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analisis5Porque',
        ),
    ]
