# Generated by Django 4.2 on 2024-11-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_MP', models.TextField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=12, null=True)),
                ('ahorro', models.DecimalField(blank=True, decimal_places=0, default='0', max_digits=12, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('subarea', models.CharField(blank=True, max_length=100, null=True)),
                ('maquina', models.CharField(blank=True, max_length=100, null=True)),
                ('pilar', models.CharField(blank=True, max_length=100, null=True)),
                ('impacto', models.TextField(blank=True, null=True)),
                ('kpi_iceo', models.CharField(blank=True, max_length=100, null=True)),
                ('kpi_secundario', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('que_ocurre', models.TextField(blank=True, null=True, verbose_name='¿Qué ocurre? ¿En qué parte de la máquina o material se visualiza el problema?')),
                ('donde_ocurre', models.TextField(blank=True, null=True, verbose_name='¿Dónde ocurre? Producto, equipo, zona de la máquina, etc.')),
                ('como_ocurre', models.TextField(blank=True, null=True, verbose_name='¿Cómo ocurre? Describir desde el punto de vista físico el mecanismo de acción visibilizado en el momento.')),
                ('cuando_ocurre', models.TextField(blank=True, null=True, verbose_name='¿Cuándo ocurrió? Producción, arranque, saneado, cambio de formato, mantención, etc.')),
                ('quien_intervino', models.TextField(blank=True, null=True, verbose_name='¿Quién pudo influir o interviene?')),
                ('perdida', models.TextField(blank=True, null=True, verbose_name='¿Cuánto es la pérdida asociada? (horas, kilos, cajas, botellas, dinero, etc)')),
                ('resumen', models.TextField(blank=True, null=True, verbose_name='Resumen del problema')),
                ('imagen_falla_funcional', models.ImageField(blank=True, null=True, upload_to='imagenes_fallas/')),
                ('condicion_basica', models.TextField(blank=True, null=True, verbose_name='¿Existe un estándar (procedimiento/instructivo/formato definido)?, ¿Es conocido por todos, existe un entrenamiento (Registro de capacitación/LUP) ?¿Cumple mantenciones preventivas?')),
                ('imagen_funcionamiento', models.ImageField(blank=True, null=True, upload_to='imagenes_funcionamiento/')),
                ('ISHIKAWA', models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True, verbose_name='Escoja una de las 6 M')),
                ('desarrollo', models.TextField(blank=True, null=True, verbose_name='Describa causa raíz')),
                ('Accion_Preventiva', models.TextField(blank=True, null=True)),
                ('Accion_Preventiva_2', models.TextField(blank=True, null=True)),
                ('Accion_Preventiva_3', models.TextField(blank=True, null=True)),
                ('Accion_Preventiva_4', models.TextField(blank=True, null=True)),
                ('Fecha_inicio2', models.DateField(blank=True, null=True)),
                ('Fecha_inicio2_2', models.DateField(blank=True, null=True)),
                ('Fecha_inicio2_3', models.DateField(blank=True, null=True)),
                ('Fecha_inicio2_4', models.DateField(blank=True, null=True)),
                ('Fecha_compromiso2', models.DateField(blank=True, null=True)),
                ('Fecha_compromiso2_2', models.DateField(blank=True, null=True)),
                ('Fecha_compromiso2_3', models.DateField(blank=True, null=True)),
                ('Fecha_compromiso2_4', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10)),
                ('estado_2', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10)),
                ('estado_3', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10)),
                ('estado_4', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10)),
                ('Fecha_cierre_paso4', models.DateField(blank=True, null=True)),
                ('Fecha_cierre_paso4_2', models.DateField(blank=True, null=True)),
                ('Fecha_cierre_paso4_3', models.DateField(blank=True, null=True)),
                ('Fecha_cierre_paso4_4', models.DateField(blank=True, null=True)),
                ('Estandarizacion', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso3', models.DateField(blank=True, null=True)),
                ('Estandarizacion_2', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso3_2', models.DateField(blank=True, null=True)),
                ('Estandarizacion_3', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso3_3', models.DateField(blank=True, null=True)),
                ('Estandarizacion_4', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso3_4', models.DateField(blank=True, null=True)),
                ('Expansion', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso4', models.DateField(blank=True, null=True)),
                ('Expansion_2', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso4_2', models.DateField(blank=True, null=True)),
                ('Expansion_3', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso4_3', models.DateField(blank=True, null=True)),
                ('Expansion_4', models.TextField(blank=True, null=True)),
                ('Fecha_compromiso4_4', models.DateField(blank=True, null=True)),
                ('areas_aplicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('Responsable2', models.ManyToManyField(blank=True, related_name='responsable2', to='Kaizen.miembroequipo')),
                ('Responsable2_2', models.ManyToManyField(blank=True, related_name='responsable2_2', to='Kaizen.miembroequipo')),
                ('Responsable2_3', models.ManyToManyField(blank=True, related_name='responsable2_3', to='Kaizen.miembroequipo')),
                ('Responsable2_4', models.ManyToManyField(blank=True, related_name='responsable2_4', to='Kaizen.miembroequipo')),
                ('Responsable3', models.ManyToManyField(blank=True, related_name='responsable3', to='Kaizen.miembroequipo')),
                ('Responsable3_2', models.ManyToManyField(blank=True, related_name='responsable3_2', to='Kaizen.miembroequipo')),
                ('Responsable3_3', models.ManyToManyField(blank=True, related_name='responsable3_3', to='Kaizen.miembroequipo')),
                ('Responsable3_4', models.ManyToManyField(blank=True, related_name='responsable3_4', to='Kaizen.miembroequipo')),
                ('Responsable4', models.ManyToManyField(blank=True, related_name='responsable4', to='Kaizen.miembroequipo')),
                ('Responsable4_2', models.ManyToManyField(blank=True, related_name='responsable4_2', to='Kaizen.miembroequipo')),
                ('Responsable4_3', models.ManyToManyField(blank=True, related_name='responsable4_3', to='Kaizen.miembroequipo')),
                ('Responsable4_4', models.ManyToManyField(blank=True, related_name='responsable4_4', to='Kaizen.miembroequipo')),
                ('miembros_equipo', models.ManyToManyField(to='Kaizen.miembroequipo')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenKaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_Kaizen/')),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Kaizen.kaizen')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenFuncionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_funcionamiento/')),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_funcionamiento', to='Kaizen.kaizen')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenDespues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_despues/')),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_despues', to='Kaizen.kaizen')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenAntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_antes/')),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_antes', to='Kaizen.kaizen')),
            ],
        ),
    ]
