# Generated by Django 4.2 on 2024-11-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kaizen',
            old_name='Nombre_MP',
            new_name='Nombre_Kaizen',
        ),
    ]
