# Generated by Django 4.2 on 2024-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0002_rename_nombre_mp_kaizen_nombre_kaizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='lider',
            field=models.ManyToManyField(blank=True, related_name='lider', to='Kaizen.miembroequipo'),
        ),
    ]
