# Generated by Django 4.2 on 2024-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0003_kaizen_lider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaizen',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='impacto',
        ),
        migrations.AddField(
            model_name='kaizen',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
