# Generated by Django 4.2 on 2024-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0006_imagenkaizen_height_imagenkaizen_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='nombre',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
