# Generated by Django 4.2 on 2024-11-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0007_kaizen_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='width',
        ),
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='x',
        ),
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='y',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='imagenkaizen',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_Kaizen/'),
        ),
    ]
