# Generated by Django 4.2 on 2024-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0008_remove_imagenkaizen_height_remove_imagenkaizen_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaizenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
