# Generated by Django 4.2 on 2024-11-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0009_kaizenimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KaizenImage',
        ),
    ]
