# Generated by Django 4.2 on 2024-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0011_kaizenimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='kaizen',
        ),
        migrations.AddField(
            model_name='imagenkaizen',
            name='height',
            field=models.CharField(default='100px', max_length=50),
        ),
        migrations.AddField(
            model_name='imagenkaizen',
            name='kaizen_id',
            field=models.IntegerField(default=1),  # Usa un valor que tenga sentido en tu caso
        ),
        migrations.AddField(
            model_name='imagenkaizen',
            name='width',
            field=models.CharField(default='100px', max_length=50),
        ),
        migrations.AddField(
            model_name='imagenkaizen',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='imagenkaizen',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='imagenkaizen',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_kaizen/'),
        ),
        migrations.DeleteModel(
            name='KaizenImage',
        ),
    ]
