# Generated by Django 4.2 on 2024-11-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0012_remove_imagenkaizen_kaizen_imagenkaizen_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='height',
        ),
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='kaizen_id',
        ),
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='width',
        ),
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='x',
        ),
        migrations.RemoveField(
            model_name='imagenkaizen',
            name='y',
        ),
        migrations.AddField(
            model_name='imagenkaizen',
            name='kaizen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Kaizen.kaizen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kaizen',
            name='alcanzable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='especifico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='medible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='realista',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='tiempo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenkaizen',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_Kaizen/'),
        ),
    ]
