# Generated by Django 4.2 on 2024-11-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0014_kaizen_deployement_imagendeploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaizen',
            name='deployement',
        ),
        migrations.AddField(
            model_name='kaizen',
            name='deploy',
            field=models.TextField(blank=True, null=True, verbose_name='Deployement de Pérdida'),
        ),
    ]
