# Generated by Django 4.2 on 2024-11-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0015_remove_kaizen_deployement_kaizen_deploy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagendespues',
            name='kaizen',
        ),
        migrations.DeleteModel(
            name='ImagenAntes',
        ),
        migrations.DeleteModel(
            name='ImagenDespues',
        ),
    ]
