# Generated by Django 4.2 on 2024-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0019_rename_deploy_kaizen_deployement'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='imagen_deploy',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_deploy/'),
        ),
    ]
