# Generated by Django 4.2 on 2024-11-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0023_remove_imagendespues_kaizen_delete_imagenantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kaizen',
            name='como_ocurre',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='cuando_ocurre',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='donde_ocurre',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='perdida',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='que_ocurre',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='quien_intervino',
        ),
        migrations.RemoveField(
            model_name='kaizen',
            name='resumen',
        ),
        migrations.AddField(
            model_name='kaizen',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del problema'),
        ),
    ]
