# Generated by Django 4.2 on 2024-11-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0024_remove_kaizen_como_ocurre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenKaizen',
        ),
    ]
