# Generated by Django 4.2 on 2024-11-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0025_delete_imagenkaizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_descripcion/')),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_descripcion', to='Kaizen.kaizen')),
            ],
        ),
    ]
