# Generated by Django 4.2 on 2024-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0026_imagendescripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='seleccion',
            field=models.CharField(choices=[('visual', 'Visual'), ('unificado', 'Unificar'), ('5W & H', '5W & H'), ('otros, especificar', 'Otros, especifico')], default='no_aplica', max_length=20, null=True, verbose_name='seleccion'),
        ),
    ]
