# Generated by Django 4.2 on 2024-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0027_kaizen_seleccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='seleccion_paso2',
            field=models.CharField(choices=[('principio de funcionamiento', 'Principio de funcionamiento'), ('verificar parametro', 'Verificar parámetros'), ('layouts', 'Layout'), ('grafica de recorrido', 'Gráfica de recorrido'), ('otros, especificar', 'Otros, especifico')], default='no_aplica', max_length=30, null=True, verbose_name='Selección:'),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='condicion_basica',
            field=models.TextField(blank=True, null=True, verbose_name='Entender los principios de funcionamiento y parámetros -> describir el modo de falla -> restaurar las condiciones básicas (relacionadas)'),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='seleccion',
            field=models.CharField(choices=[('visual', 'Visual'), ('unificado', 'Unificar'), ('5W & H', '5W & H'), ('otros, especificar', 'Otros, especifico')], default='no_aplica', max_length=20, null=True, verbose_name='Selección:'),
        ),
        migrations.DeleteModel(
            name='ImagenFuncionamiento',
        ),
    ]
