# Generated by Django 4.2 on 2024-11-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0029_kaizen_ishikawa_2_kaizen_ishikawa_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='seleccion_paso4',
            field=models.CharField(blank=True, choices=[('moc', 'MOC'), ('otros, especificar', 'Otros, especificar')], max_length=100, null=True, verbose_name='Selección'),
        ),
        migrations.AlterField(
            model_name='kaizen',
            name='desarrollo',
            field=models.TextField(blank=True, null=True, verbose_name="Identificar posibles causas basados en el(los) modo(s) de falla(s) -> definir la hipótesis y verificar -> ligar la(s) causa(s) raíz con las 6M's"),
        ),
    ]
