# Generated by Django 4.2 on 2024-11-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0030_kaizen_seleccion_paso4_alter_kaizen_desarrollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaizen',
            name='seleccion_paso4',
            field=models.CharField(choices=[('moc', 'MOC'), ('otros, especificar', 'Otros, especificar')], default='no_aplica', max_length=30, null=True, verbose_name='Selección:'),
        ),
        migrations.CreateModel(
            name='ImagenDefinir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_definir/')),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_definir', to='Kaizen.kaizen')),
            ],
        ),
    ]
