# Generated by Django 4.2 on 2024-11-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0032_kaizen_accion_preventiva_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='estandarizacion_TA',
            field=models.TextField(blank=True, null=True, verbose_name='Estandarización de perdidas'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='expansion_TA',
            field=models.TextField(blank=True, null=True, verbose_name='Expansión de perdidas'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='seleccion_paso5',
            field=models.CharField(choices=[('estándar nuevo LUP', 'Estándar nuevo LUP'), ('poka yoke', 'Poka Yoke'), ('gestión visual', 'Gestión Visual'), ('disparador', 'Disparador'), ('otros, especificar', 'Otros, especificar')], default='no_aplica', max_length=30, null=True, verbose_name='Selección:'),
        ),
    ]
