# Generated by Django 4.2 on 2024-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0034_alter_kaizen_seleccion_paso5_imagenexpansion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon',
            field=models.ManyToManyField(blank=True, related_name='respon', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
    ]
