# Generated by Django 4.2 on 2024-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0035_kaizen_fechacompr_kaizen_ishikawa_acciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones',
            field=models.DateField(blank=True, null=True),
        ),
    ]
