# Generated by Django 4.2 on 2024-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0036_kaizen_fechacierre_acciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones',
            field=models.DateField(blank=True, null=True),
        ),
    ]
