# Generated by Django 4.2 on 2024-11-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0038_kaizen_estado_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCierre_acciones_9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaCompr_9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='FechaInicio_acciones_9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_10',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_2',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_3',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_4',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_5',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_6',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_7',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_8',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='ISHIKAWA_acciones_9',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_10',
            field=models.ManyToManyField(blank=True, related_name='respon_10', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_2',
            field=models.ManyToManyField(blank=True, related_name='respon_2', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_3',
            field=models.ManyToManyField(blank=True, related_name='respon_3', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_4',
            field=models.ManyToManyField(blank=True, related_name='respon_4', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_5',
            field=models.ManyToManyField(blank=True, related_name='respon_5', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_6',
            field=models.ManyToManyField(blank=True, related_name='respon_6', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_7',
            field=models.ManyToManyField(blank=True, related_name='respon_7', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_8',
            field=models.ManyToManyField(blank=True, related_name='respon_8', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='Respon_9',
            field=models.ManyToManyField(blank=True, related_name='respon_9', to='Kaizen.miembroequipo'),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='accion_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_10',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_2',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_3',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_4',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_5',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_6',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_7',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_8',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='estado_accion_9',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='observacion_9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_10',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_2',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_3',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_4',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_5',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_6',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_7',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_8',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='opciones_acciones_9',
            field=models.CharField(blank=True, choices=[('accion imediata (correccion)', 'Acción imediata (corrección)'), ('accion orientada causa raiz (correctiva)', 'Acción orientada causa raíz (correctiva)'), ('accion preventiva', 'Acción preventiva')], max_length=100, null=True),
        ),
    ]
