# Generated by Django 4.2 on 2024-12-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAPM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hapm',
            name='descripcion_senal',
        ),
        migrations.RemoveField(
            model_name='hapm',
            name='senal_antes',
        ),
    ]
