# Generated by Django 4.2 on 2024-12-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAPM', '0002_remove_hapm_descripcion_senal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hapm',
            name='falla_funcional',
        ),
        migrations.AddField(
            model_name='hapm',
            name='que_accion',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué acción realiza el Operador al detectar el modo de falla?¿De qué forma realiza la asistencia? (Correctiva o preventiva)'),
        ),
    ]
