# Generated by Django 4.2 on 2024-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAPM', '0003_remove_hapm_falla_funcional_hapm_que_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hapm',
            name='modo_falla',
            field=models.TextField(blank=True, null=True, verbose_name='¿Quién estaba presente cuando ocurrió? ¿El problema pasa en todos los turnos?'),
        ),
        migrations.AlterField(
            model_name='hapm',
            name='que_accion',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuál es el modo de falla priorizado?¿A qué indicador impacta?'),
        ),
    ]
