# Generated by Django 4.2 on 2024-12-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HAPM', '0004_hapm_modo_falla_alter_hapm_que_accion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hapm',
            name='imagen_falla',
        ),
        migrations.CreateModel(
            name='ImagenFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Imagen_Falla/')),
                ('hapm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagen_Falla', to='HAPM.hapm')),
            ],
        ),
    ]
