# Generated by Django 4.2 on 2024-09-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paso1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_ocurre', models.TextField(verbose_name='¿Qué ocurre? ¿En qué parte de la máquina o materal se visualiza el problema?')),
                ('como_ocurre', models.TextField(verbose_name='¿Cómo ocurre? Describir desde el punto de vista físico el mecanismo de acción visibilizado en el momento.')),
                ('donde_ocurre', models.TextField(verbose_name='¿Dónde ocurre? Producto, equipo, zona de la máquina, etc.')),
                ('cuando_ocurre', models.TextField(verbose_name='¿Cuando ocurrió? Producción, arranque, saneado, cambio de formato, mantención, etc.')),
                ('quien_presente', models.TextField(verbose_name='¿Quién estaba presente cuando ocurrió? ¿El problema pasa en todos los turnos?')),
                ('senal_antes', models.CharField(choices=[('alarma', 'Alarma'), ('fuga', 'Fuga'), ('cavitacion', 'Cavitación'), ('ruido', 'Ruido'), ('otros', 'Otros'), ('nia', 'N/A')], max_length=100, verbose_name='Señal antes de que ocurra el problema')),
                ('descripcion_senal', models.TextField(blank=True, null=True, verbose_name='Descripción de la señal')),
                ('falla_funcional', models.TextField(help_text='Describa la falla funcional que se observó', verbose_name='Falla funcional')),
                ('imagen_falla_funcional', models.ImageField(blank=True, null=True, upload_to='imagenes_fallas/')),
            ],
        ),
        migrations.CreateModel(
            name='Porque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('subarea', models.CharField(max_length=100)),
                ('maquina', models.CharField(max_length=100)),
                ('pilar', models.CharField(max_length=100)),
                ('impacto', models.TextField()),
                ('kpi_iceo', models.CharField(max_length=100)),
                ('kpi_secundario', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('miembros_equipo', models.ManyToManyField(to='porque.miembroequipo')),
            ],
        ),
    ]
