# Generated by Django 4.2 on 2024-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='puntaje',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
