# Generated by Django 5.0.7 on 2024-08-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porque5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('categoria', models.CharField(max_length=50)),
                ('prioridad', models.CharField(max_length=20)),
                ('seguimiento', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MiModelo',
        ),
    ]
