# Generated by Django 4.2 on 2024-09-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='principio_funcionamiento',
            field=models.TextField(blank=True, null=True, verbose_name='aaaaaaaaaaaaaaaaa'),
        ),
    ]
