# Generated by Django 4.2 on 2024-10-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='impacto',
            field=models.TextField(null=True),
        ),
    ]
