# Generated by Django 5.1.1 on 2024-09-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='color1',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='porque',
            name='color2',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='porque',
            name='color3',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='porque',
            name='color4',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='porque',
            name='color5',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
