# Generated by Django 4.2 on 2024-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='Responsable1',
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable1',
            field=models.ManyToManyField(related_name='Responsable', to='porque.miembroequipo'),
        ),
    ]
