# Generated by Django 4.2 on 2024-09-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porque',
            old_name='linea',
            new_name='maquina',
        ),
        migrations.RenameField(
            model_name='porque',
            old_name='subcategoria',
            new_name='subarea',
        ),
    ]
