# Generated by Django 5.1.1 on 2024-09-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0002_porque_principio_funcionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='condiciones_basicas',
            field=models.TextField(blank=True, null=True, verbose_name='Verificar condiciones básicas definidas e identificar desviaciones que impacten en el problema'),
        ),
        migrations.AddField(
            model_name='porque',
            name='imagen_funcionamiento',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_funcionamiento/'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='principio_funcionamiento',
            field=models.TextField(blank=True, null=True, verbose_name='Comprender el principio de funcionamiento de la máquina o proceso, incluyendo estándares y parámetros de trabajo'),
        ),
    ]
