# Generated by Django 5.0.7 on 2024-08-06 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0002_porque5_delete_mimodelo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porque5',
            new_name='Porque',
        ),
    ]
