# Generated by Django 4.2 on 2024-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0002_alter_porque_responsable1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA_2',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA_3',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA_4',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA_5',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA_6',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA_7',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='ISHIKAWA_8',
            field=models.CharField(blank=True, choices=[('Máquina', 'Máquina'), ('Método', 'Método'), ('Medio Ambiente', 'Medio Ambiente'), ('Material', 'Material'), ('Medición', 'Medición'), ('Mano de Obra', 'Mano de Obra')], max_length=100, null=True),
        ),
    ]
