# Generated by Django 4.2 on 2024-09-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0002_rename_linea_porque_maquina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='porque',
            name='miembros_equipo',
        ),
        migrations.AddField(
            model_name='porque',
            name='miembros_equipo',
            field=models.ManyToManyField(to='porque.miembroequipo'),
        ),
    ]
