# Generated by Django 5.1.1 on 2024-09-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0002_porque_color1_porque_color2_porque_color3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='validado1',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado2',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado4',
        ),
    ]
