# Generated by Django 4.2 on 2024-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0002_alter_porque_impacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='impacto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
