# Generated by Django 4.2 on 2024-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0002_delete_paso1_porque_como_ocurre_porque_cuando_ocurre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='como_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cómo ocurre?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='cuando_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Cuándo ocurre?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='donde_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Dónde ocurre?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='falla_funcional',
            field=models.TextField(blank=True, null=True, verbose_name='Falla funcional'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='impacto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='kpi_iceo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='kpi_secundario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='maquina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='pilar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='que_ocurre',
            field=models.TextField(blank=True, null=True, verbose_name='¿Qué ocurre?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='quien_presente',
            field=models.TextField(blank=True, null=True, verbose_name='¿Quién estaba presente?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='senal_antes',
            field=models.CharField(blank=True, choices=[('alarma', 'Alarma'), ('fuga', 'Fuga'), ('cavitacion', 'Cavitación'), ('ruido', 'Ruido'), ('otros', 'Otros'), ('nia', 'N/A')], max_length=100, null=True, verbose_name='Señal antes de que ocurra el problema'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='subarea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='porque',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
