# Generated by Django 4.2 on 2024-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0003_miembroequipo_remove_porque_miembros_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembroequipo',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
