# Generated by Django 4.2 on 2024-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0003_remove_porque_responsable1_porque_rresponsable1'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='Accion_correctiva_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso1_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='RResponsable1_2',
            field=models.ManyToManyField(blank=True, related_name='responsable1_2', to='porque.miembroequipo'),
        ),
    ]
