# Generated by Django 4.2 on 2024-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0003_alter_porque_impacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
