# Generated by Django 5.1.1 on 2024-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0003_remove_porque_validado1_remove_porque_validado2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='color4',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='color5',
        ),
        migrations.AddField(
            model_name='porque',
            name='validado1',
            field=models.BooleanField(default=False, verbose_name='Validado (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='validado2',
            field=models.BooleanField(default=False, verbose_name='Validado (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='validado3',
            field=models.BooleanField(default=False, verbose_name='Validado (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='validado4',
            field=models.BooleanField(default=False, verbose_name='Validado (4)'),
        ),
    ]
