# Generated by Django 4.2 on 2024-10-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0003_porque_ishikawa_porque_ishikawa_2_porque_ishikawa_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='Estandarizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Estandarizacion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Estandarizacion_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Estandarizacion_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso3_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso3_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso3_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable3',
            field=models.ManyToManyField(blank=True, related_name='responsable3', to='porque.miembroequipo'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable3_2',
            field=models.ManyToManyField(blank=True, related_name='responsable3_2', to='porque.miembroequipo'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable3_3',
            field=models.ManyToManyField(blank=True, related_name='responsable3_3', to='porque.miembroequipo'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable3_4',
            field=models.ManyToManyField(blank=True, related_name='responsable3_4', to='porque.miembroequipo'),
        ),
    ]
