# Generated by Django 5.1.1 on 2024-09-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0004_porque_ejecuto_lila_porque_lila_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='imagen_falla',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_funcionamiento/'),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla',
            field=models.TextField(blank=True, null=True, verbose_name='El modo de falla corresponde al evento o situación que causa la falla funcional. Ej: presión inestable por válvula rota, inspector detecta elemento extraño pero no lo rechaza, inspector no detecta elemento extraño, sulfatación de sensor de seguridad, etc.'),
        ),
    ]
