# Generated by Django 4.2 on 2024-10-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0004_porque_accion_correctiva_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porque',
            old_name='RResponsable1',
            new_name='Responsable1',
        ),
        migrations.RenameField(
            model_name='porque',
            old_name='RResponsable1_2',
            new_name='Responsable1_2',
        ),
        migrations.AddField(
            model_name='porque',
            name='Accion_correctiva_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Accion_correctiva_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso1_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso1_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable1_3',
            field=models.ManyToManyField(blank=True, related_name='responsable1_3', to='porque.miembroequipo'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable1_4',
            field=models.ManyToManyField(blank=True, related_name='responsable1_4', to='porque.miembroequipo'),
        ),
    ]
