# Generated by Django 4.2 on 2024-09-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0004_miembroequipo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paso2',
        ),
    ]
