# Generated by Django 4.2 on 2024-10-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0004_alter_porque_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
