# Generated by Django 5.0.7 on 2024-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0004_paso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.CharField(max_length=200)),
                ('campo3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paso4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.CharField(max_length=200)),
                ('campo3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paso5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.CharField(max_length=200)),
                ('campo3', models.TextField()),
            ],
        ),
    ]
