# Generated by Django 4.2 on 2024-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0004_porque_estandarizacion_porque_estandarizacion_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='Expansion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Expansion_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Expansion_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Expansion_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso4_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso4_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso4_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable4',
            field=models.ManyToManyField(blank=True, related_name='responsable4', to='porque.miembroequipo'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable4_2',
            field=models.ManyToManyField(blank=True, related_name='responsable4_2', to='porque.miembroequipo'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable4_3',
            field=models.ManyToManyField(blank=True, related_name='responsable4_3', to='porque.miembroequipo'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable4_4',
            field=models.ManyToManyField(blank=True, related_name='responsable4_4', to='porque.miembroequipo'),
        ),
    ]
