# Generated by Django 5.1.1 on 2024-09-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0004_remove_porque_color1_remove_porque_color2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='validado5',
            field=models.BooleanField(default=False, verbose_name='Validado (5)'),
        ),
    ]
