# Generated by Django 4.2 on 2024-09-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0005_porque_validado5'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='color1',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='color2',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='color3',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='color4',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='color5',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color (5)'),
        ),
    ]
