# Generated by Django 4.2 on 2024-10-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0005_rename_rresponsable1_porque_responsable1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='Responsable1',
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Responsable1', to='porque.miembroequipo'),
        ),
    ]
