# Generated by Django 4.2 on 2024-10-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0005_porque_expansion_porque_expansion_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
