# Generated by Django 5.0.7 on 2024-09-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0005_paso3_paso4_paso5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paso2',
            old_name='campo1',
            new_name='campo_1',
        ),
    ]
