# Generated by Django 4.2 on 2024-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0005_delete_paso2'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='categoria',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='porque',
            name='subcategoria',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
