# Generated by Django 5.1.1 on 2024-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0005_porque_imagen_falla_porque_modo_falla'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='causas_raiz',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
