# Generated by Django 4.2 on 2024-11-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0006_porque_miniproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFallaFun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Imagen_FallaFun/')),
                ('porque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagen_FallaFun', to='porque.porque')),
            ],
        ),
    ]
