# Generated by Django 4.2 on 2024-09-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0006_porque_categoria_porque_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField(help_text='Describe el problema en detalle', verbose_name='Descripción del problema')),
                ('donde_ocurre', models.TextField(help_text='Producto, equipo, zona de la máquina, etc.', verbose_name='¿Dónde ocurre?')),
                ('como_ocurre', models.TextField(help_text='Describe desde el punto de vista físico y el mecanismo de acción', verbose_name='¿Cómo ocurre?')),
                ('cuando_ocurre', models.TextField(help_text='Producción, arranque, saneado, etc.', verbose_name='¿Cuándo ocurrió?')),
                ('quien_presente', models.TextField(help_text='El problema pasa en todos los turnos?', verbose_name='¿Quién estaba presente?')),
                ('senal_antes', models.CharField(choices=[('alarma', 'Alarma'), ('fuga', 'Fuga'), ('cavitacion', 'Cavitación'), ('ruido', 'Ruido'), ('otros', 'Otros'), ('nia', 'N/A')], max_length=100, verbose_name='Señal antes de que ocurra el problema')),
                ('descripcion_senal', models.TextField(blank=True, null=True, verbose_name='Descripción de la señal')),
            ],
        ),
    ]
