# Generated by Django 4.2 on 2024-09-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0007_alter_porque_color1_alter_porque_color2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='validado1',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado2',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado4',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado5',
        ),
    ]
