# Generated by Django 5.0.7 on 2024-09-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0007_delete_paso2_delete_paso3_delete_paso4_delete_paso5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paso2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_1', models.CharField(max_length=100)),
                ('campo2', models.CharField(max_length=200)),
                ('campo3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paso3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.CharField(max_length=200)),
                ('campo3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paso4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.CharField(max_length=200)),
                ('campo3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paso5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.CharField(max_length=200)),
                ('campo3', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo1_paso3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo1_paso4',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo1_paso5',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo2',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo2_paso3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo2_paso4',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo2_paso5',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo3_paso3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo3_paso4',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo3_paso5',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='campo_1',
        ),
        migrations.AlterField(
            model_name='porque',
            name='asunto',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='porque',
            name='categoria',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='porque',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='porque',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='porque',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='porque',
            name='prioridad',
            field=models.CharField(max_length=20),
        ),
    ]
