# Generated by Django 4.2 on 2024-09-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0007_paso1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paso1',
            name='como_ocurre',
            field=models.TextField(verbose_name='¿Cómo ocurre?'),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='cuando_ocurre',
            field=models.TextField(verbose_name='¿Cuándo ocurrió?'),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='descripcion_problema',
            field=models.TextField(verbose_name='Descripción del problema'),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='donde_ocurre',
            field=models.TextField(verbose_name='¿Dónde ocurre?'),
        ),
        migrations.AlterField(
            model_name='paso1',
            name='quien_presente',
            field=models.TextField(verbose_name='¿Quién estaba presente?'),
        ),
    ]
