# Generated by Django 4.2 on 2024-11-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0007_imagenfallafun'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFuncionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Imagen_Funcionamiento/')),
                ('porque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagen_Funcionamiento', to='porque.porque')),
            ],
        ),
    ]
