# Generated by Django 4.2 on 2024-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0008_alter_paso1_como_ocurre_alter_paso1_cuando_ocurre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paso1',
            name='falla_funcional',
            field=models.TextField(default='', help_text='Describa la falla funcional que se observó', verbose_name='Falla funcional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paso1',
            name='imagen_falla_funcional',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_fallas/'),
        ),
    ]
