# Generated by Django 4.2 on 2024-11-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0001_initial'),
        ('porque', '0008_imagenfuncionamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='kaizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Kaizen.kaizen'),
        ),
    ]
