# Generated by Django 4.2 on 2024-12-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0039_kaizen_fechacierre_acciones_10_and_more'),
        ('porque', '0009_porque_kaizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='kaizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='porques', to='Kaizen.kaizen'),
        ),
    ]
