# Generated by Django 4.2 on 2024-09-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0009_paso1_falla_funcional_paso1_imagen_falla_funcional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paso1',
            name='descripcion_problema',
        ),
        migrations.AddField(
            model_name='paso1',
            name='que_ocurre',
            field=models.TextField(default='', verbose_name='¿Qué ocurre? ¿En qué parte de la máquina o materal se visualiza el problema?'),
            preserve_default=False,
        ),
    ]
