# Generated by Django 4.2 on 2024-09-30 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0009_rename_color1_porque_color_validacion1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='validado1',
        ),
    ]
