# Generated by Django 4.2 on 2024-09-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0010_remove_porque_validado1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='validado2',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado3',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado4',
        ),
        migrations.RemoveField(
            model_name='porque',
            name='validado5',
        ),
    ]
