# Generated by Django 4.2 on 2024-09-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0011_remove_porque_validado2_remove_porque_validado3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='Raiz',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
    ]
