# Generated by Django 4.2 on 2024-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0012_porque_raiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porque',
            old_name='modo_falla',
            new_name='modo_falla_paso3',
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso2',
            field=models.TextField(blank=True, null=True, verbose_name='El modo de falla corresponde al evento o situación que causa la falla funcional. Ej: presión inestable por válvula rota, inspector detecta elemento extraño pero no lo rechaza, inspector no detecta elemento extraño, sulfatación de sensor de seguridad, etc.'),
        ),
    ]
