# Generated by Django 4.2 on 2024-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0013_rename_modo_falla_porque_modo_falla_paso3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porque',
            name='ejecuto_lila',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Se ejecutó correctamente el LILA?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='lila_asociado',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Hay LILA asociado a la máquina?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='mantenimiento_no_ejecutado',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Hay actividades de mantenimiento no ejecutadas asociadas a la falla funcional (revisar plan de 52 semanas)?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='materiales_calidad',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Los materiales cumplen con las especificaciones de calidad?'),
        ),
        migrations.AlterField(
            model_name='porque',
            name='tarjetas_atrasadas',
            field=models.CharField(choices=[('no', 'NO'), ('no_aplica', 'NO APLICA'), ('si', 'SI')], default='no_aplica', max_length=10, null=True, verbose_name='¿Hay tarjetas atrasadas o pendientes asociadas a la falla funcional?'),
        ),
    ]
