# Generated by Django 4.2 on 2024-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0014_alter_porque_ejecuto_lila_alter_porque_lila_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='color_validacion6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
    ]
