# Generated by Django 4.2 on 2024-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0015_porque_color_validacion6_porque_porque6'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='color_validacion7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
    ]
