# Generated by Django 4.2 on 2024-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0016_porque_color_validacion7_porque_porque7'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='color_validacion1_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion2_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion3_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion4_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion5_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion6_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion7_2',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso3_2',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='porque',
            name='num_filas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque1_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque2_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque3_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque4_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque5_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7_2',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
    ]
