# Generated by Django 4.2 on 2024-10-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0018_remove_porque_num_filas_porque_raiz_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='Raiz_3',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Raiz_4',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion1_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion1_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion2_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion2_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion3_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion3_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion4_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion4_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion5_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion5_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion6_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion6_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion7_3',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion7_4',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso3_3',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso3_4',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque1_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque1_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque2_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque2_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque3_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque3_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque4_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque4_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque5_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque5_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7_3',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7_4',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
    ]
