# Generated by Django 4.2 on 2024-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0019_porque_raiz_3_porque_raiz_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='Raiz_5',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Raiz_6',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Raiz_7',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='porque',
            name='Raiz_8',
            field=models.TextField(blank=True, null=True, verbose_name='Raíz'),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion1_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion1_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion1_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion1_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion2_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion2_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion2_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion2_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion3_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion3_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion3_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion3_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion4_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion4_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion4_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion4_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion5_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion5_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion5_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion5_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion6_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion6_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion6_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion6_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion7_5',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion7_6',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion7_7',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='color_validacion7_8',
            field=models.CharField(choices=[('white', 'Blanco'), ('green', 'Verde'), ('red', 'Rojo')], default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso3_5',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso3_6',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso3_7',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='porque',
            name='modo_falla_paso3_8',
            field=models.TextField(blank=True, null=True, verbose_name='Modo de Falla'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque1_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque1_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque1_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque1_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (1)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque2_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque2_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque2_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque2_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (2)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque3_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque3_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque3_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque3_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (3)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque4_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque4_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque4_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque4_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (4)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque5_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque5_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque5_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque5_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (5)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque6_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (6)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7_5',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7_6',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7_7',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
        migrations.AddField(
            model_name='porque',
            name='porque7_8',
            field=models.TextField(blank=True, null=True, verbose_name='¿POR QUÉ? (7)'),
        ),
    ]
