# Generated by Django 4.2 on 2024-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0020_porque_raiz_5_porque_raiz_6_porque_raiz_7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='areas',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
