# Generated by Django 4.2 on 2024-10-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0021_porque_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='areas',
        ),
    ]
