# Generated by Django 4.2 on 2024-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0022_remove_porque_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='areas_aplicables',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
