# Generated by Django 4.2 on 2024-10-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0023_porque_areas_aplicables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='porque',
            name='areas_aplicables',
        ),
    ]
