# Generated by Django 4.2 on 2024-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0024_remove_porque_areas_aplicables'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='areas_aplicacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
