# Generated by Django 4.2 on 2024-10-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porque', '0025_porque_areas_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='porque',
            name='Accion_Preventiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Accion_correctiva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Fecha_compromiso2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porque',
            name='Responsable2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
