# Generated by Django 4.2 on 2024-12-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HAPM', '0005_remove_hapm_imagen_falla_imagenfalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisuHAPMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_4', models.BooleanField(default=False)),
                ('porcentaje', models.IntegerField(default=0)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('Kaizen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HAPM.hapm')),
            ],
        ),
    ]
