# Generated by Django 4.2 on 2024-12-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORR', '0003_rename_orr_imagendefinir_orr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagendefinir',
            old_name='Orr',
            new_name='orr',
        ),
        migrations.RenameField(
            model_name='imagendeploy',
            old_name='Orr',
            new_name='orr',
        ),
        migrations.RenameField(
            model_name='imagendescripcion',
            old_name='Orr',
            new_name='orr',
        ),
        migrations.RenameField(
            model_name='imagenestandar',
            old_name='Orr',
            new_name='orr',
        ),
        migrations.RenameField(
            model_name='imagenexpansion',
            old_name='Orr',
            new_name='orr',
        ),
    ]
