# Generated by Django 4.2 on 2024-10-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porque', '0007_alter_porque_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visu5Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_4', models.BooleanField(default=False)),
                ('porcentaje', models.IntegerField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('porque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='porque.porque')),
            ],
        ),
    ]
