# Generated by Django 4.2 on 2024-10-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visu5', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visu5model',
            name='porcentaje1',
            field=models.IntegerField(default=0),
        ),
    ]
