# Generated by Django 4.2 on 2024-11-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visu5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visu5model',
            name='dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
