# Generated by Django 4.2 on 2024-12-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visu5', '0002_alter_visu5model_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='visu5model',
            name='paso_5',
            field=models.BooleanField(default=False),
        ),
    ]
