# Generated by Django 4.2 on 2024-10-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visu5', '0002_visu5model_porcentaje1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visu5model',
            name='porcentaje1',
        ),
    ]
