# Generated by Django 4.2 on 2024-11-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MiniProyecto', '0007_alter_miniproyecto_ahorro_alter_miniproyecto_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VisuMiniModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_4', models.BooleanField(default=False)),
                ('porcentaje', models.IntegerField(default=0)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('MiniProyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MiniProyecto.miniproyecto')),
            ],
        ),
    ]
