# Generated by Django 4.2 on 2024-11-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visuMini', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
