# Generated by Django 4.2 on 2024-11-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuMini', '0002_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='visuminimodel',
            name='ups',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
