# Generated by Django 4.2 on 2024-11-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visuMini', '0003_visuminimodel_ups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visuminimodel',
            name='ups',
        ),
    ]
