# Generated by Django 4.2 on 2024-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0039_kaizen_fechacierre_acciones_10_and_more'),
        ('visuKai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visukaimodel',
            name='MiniProyecto',
        ),
        migrations.AddField(
            model_name='visukaimodel',
            name='Kaizen',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Kaizen.kaizen'),
            preserve_default=False,
        ),
    ]
