# Generated by Django 4.2 on 2024-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuKai', '0002_remove_visukaimodel_miniproyecto_visukaimodel_kaizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='visukaimodel',
            name='paso_5',
            field=models.BooleanField(default=False),
        ),
    ]
